### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by developer9969** [xamarin/XamarinAndroidXMigration#32]
Hi
we would like to move to android 10 and I guess we need to start using this package in our xamarin forms. One the main reason is to start using the BiometricPrompt  . I wish essentials would include it but that is another story

When is the stable release planned? 
In many companies including the one I currently work  we are not allowed to use nugets that are not stable. Silly policy but it is what it is.

Any ideas?

Also I understand the caution approach you are taking but it would be nice if xamarin forms would officially start using android 10, is been out a year now.

many thanks

**Comment by GrigoriiVakhmistrov** [comment]
Hi,

We need a stable release version too.
Do you have any updates? If you have a release date or a roadmap, please let me know.

Thanks in advance

**Comment by irongut** [comment]
@developer9969 You do not need AndroidX to move to Android 10, just set your compile target to Android 10 in your Android project properties. [AndroidX](https://developer.android.com/jetpack/androidx) is not Android 10 it is a replacement for all the Android.Support.* libraries.

**Comment by moljac** [comment]
You should ask this in AndroidX repo:

https://github.com/xamarin/AndroidX

Migration package is just tooling and follows versioning (release) of AndroidX.

Answer: *I (we) hope to release stable soon (matter of days). There were some issues with migration and msbuild tasks/targets.*

**Comment by GrigoriiVakhmistrov** [comment]
@moljac Thanks
