### ISSUE TITLE
Migration is probably not working (or wrong usage?)

### ISSUE THREAD

**Issue by shults-s** [xamarin/XamarinAndroidXMigration#33]
Could you add an explanation in the README.md how to use this package?

## Steps to Reproduce
I installed it from NuGet and tried to rebuild the project.

## Expected Behavior
After rebuilding the project (or what?) all references (such as ```using```'s) to the support library packages will be replaced with references to AndroidX packages.

## Actual Behavior
A warning appeared with a recommendation to install some AndroidX packages. I installed them. But nothing else has changed. Even with subsequent rebuilds. The code has remained untouched and no build errors have occurred.

## Version Information
- Xamarin 16.4.000.306
- Xamarin.Android SDK 10.1.1.0
- Microsoft Visual Studio Community 2019 16.4.1

**Comment by irongut** [comment]
AndroidX migration does not make any changes to your source code, it changes your compiled code. By installing the AndroidX packages as asked you prevented further build errors. Have you checked what assemblies are in your apk / aab or what class your MainActivity descends from?

See [Introduction to AndroidX for Xamarin](https://channel9.msdn.com/Shows/XamarinShow/Introduction-to-AndroidX-for-Xamarin--The-Xamarin-Show).

**Comment by moljac** [comment]
> After rebuilding the project (or what?) all references (such as using's) to the support library 
>packages will be replaced with references to AndroidX packages.

No. The migration package does not alter the users' code. 

Closing this one.
